### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by 834799106** [sniklaus/3d-ken-burns#50] opened 2021-05-17 08:59 UTC
python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4
Traceback (most recent call last):
  File "autozoom.py", line 89, in <module>
    'objFrom': objFrom
  File "<string>", line 119, in process_autozoom
  File "<string>", line 436, in render_pointcloud
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "<string>", line 296, in launch_kernel
IndexError: list index out of range

**Comment by sniklaus** [comment] 2021-05-17 15:54
Works just fine for me.

![image](https://user-images.githubusercontent.com/1238034/118518527-102fbb00-b6ed-11eb-8762-01d66aba0d61.png)

But it seems like that `common.py` has been modified, the line numbers don't make sense. Closing this issue for now then as I can't reproduce this with the given information and there seem to be some changes in the code.

**Closed by sniklaus** 2021-05-17 15:54 UTC
