### ISSUE TITLE
When I run interfac.py it hangs

### ISSUE THREAD

**Issue by GantMan** [sniklaus/3d-ken-burns#4] opened 2019-11-20 18:46 UTC
I have to control+c to get out.  On Windows

![image](https://user-images.githubusercontent.com/997157/69267928-c61b5700-0b93-11ea-8b13-055457392374.png)

**Comment by sniklaus** [comment] 2019-11-21 12:27
Thank you for giving it a try! Would you mind elaborating what the issue is? If you run the interface nothing happens, and you cannot use it?

**Comment by sniklaus** [comment] 2019-11-23 22:18
I am closing this for now, I guess that it actually worked as intended but that it wasn't clear that one has to go to `http://localhost:8080/`in the browser to access the user interface.

**Closed by sniklaus** 2019-11-23 22:18 UTC

**Comment by GantMan** [comment] 2019-11-23 22:33
I'm an idiot.   TY - would you like a PR explaining that part?  I'd love to contribute.

**Comment by sniklaus** [comment] 2019-11-23 23:12
Thank you for offering to issue a pull request! I is already stated in the readme though, so no need to issue one. :smiley:
