### ISSUE TITLE
'NoneType' object has no attribute 'shape' happens for almost every image, why?

### ISSUE THREAD

**Issue by GuusDeKroon** [sniklaus/3d-ken-burns#27] opened 2020-03-02 21:53 UTC
Here's an example of what errors I get when running in colab, by the way when it does work, it's very cool! Congrats!
> Traceback (most recent call last):
>   File "autozoom.py", line 65, in <module>
>     intWidth = numpyImage.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'
> Traceback (most recent call last):
>   File "autozoom.py", line 65, in <module>
>     intWidth = numpyImage.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'
> Traceback (most recent call last):
>   File "autozoom.py", line 65, in <module>
>     intWidth = numpyImage.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by sniklaus** [comment] 2020-03-06 21:55
Seems like an issue with your Colab setup. My guess is that the script cannot find your image, possible due to a wrong path? I am afraid that I am unable to debug your environment that I am closing this case for now since the issue isn't with the provided code. Should you end up figuring out what the issue is then I would appreciate if you shared your findings here such that others with the same problem are able to read about it. Thanks!

**Closed by sniklaus** 2020-03-06 21:55 UTC
